### ISSUE TITLE
Tots els usuaris tenen imatge, descripcio i arxius adjunts

### ISSUE THREAD

**Issue by lilyaiza** [AWS2/BorsaDeTreball#7]
Tots els usuaris tenen:
- Imatge de perfil/logo
- Camp de descripció/presentació de la seva activitat (com a empresa o com a estudiant o com a centre)
- Arxiu adjunt (CV, tríptic, etc.)

**Comment by emieza** [comment]
Mira en aquesta referència:

**Comment by emieza** [comment]
I això per crear el camp de les categories suscrites pels usuaris:
https://docs.djangoproject.com/es/2.1/topics/db/examples/many_to_many/
