### ISSUE TITLE
Social login (OAuth Google i Microsoft) 

### ISSUE THREAD

**Issue by ncristiansa** [AWS2/BorsaDeTreball#8]

**Comment by ncristiansa** [comment]
URL OAuth: https://django-oauth-toolkit.readthedocs.io/en/latest/tutorial/tutorial_01.html

**Comment by emieza** [comment]
Creo que es preferible usar este otro, que lo tengo comprobado que va bien:

https://python-social-auth-docs.readthedocs.io/en/latest/configuration/django.html
